### ISSUE TITLE
New purchases should decrement the available seats for that showing

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#18]

**Comment by adamr5000** [comment]
I don't know about you, but whenever I try to load any page that's purchase-related, it doesn't go well. The purchase log page was crashing the program with an NpgsqlException saying {"42703: column \"payment_key\" does not exist"}. The new purchase page throws a 500 error instead. It works for you, I take it? Just trying to narrow down the culprits.

**Comment by GeorgeHahn** [comment]
Recreate your db lately? The payment model changed, so the scheme changed as well.



—

**Comment by adamr5000** [comment]
Hmm, how bizarre. I figured a remake was needed, but before, when I tried to drop and recreate, it was also throwing a 500 error. This time it worked, and now the purchase log works. The new-purchase page still throws a 500 though (below). I'll keep tinkering around it, with the time I have today before class; hopefully I can get it working and get something a bit more... substantial up by then. This computer continues to surprise.

Nancy.RequestExecutionException: Oh noes! ---> System.InvalidCastException: Unable to cast object of type 'Nancy.DynamicDictionaryValue' to type 'System.Collections.Generic.IEnumerable`1[Nancy.ViewEngines.Razor.HtmlHelpers.SelectListItem]'.
   at CallSite.Target(Closure , CallSite , Object )
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by GeorgeHahn** [comment]
Ahh, yeah that error looks like something broken in a view. I may have left things in a bad state with my last commit, I know I was dealing with a lot of similar issues last time. (We should really have some tests covering view rendering, then at least we'll know up front when things like this are broken. Thing is, we'd have to mock the db or the controllers in the test environment.)



—
